#!/bin/bash

RES=$(git show-ref --tags)
if [ -z "$RES" ]; then
    NEW_TAG=1.0.0
else
    NEW_TAG=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}')
fi
echo $NEW_TAG
#git tag $NEW_TAG -a "autogenerated tag"
#git push origin $NEW_TAG
